#!/data/data/com.termux/files/usr/bin/bash

shellnoroot(){
  # check termux-proot running or not
  if [[ $SHELL == "/bin/bash" ]];then
	#echo "[!] termux-red already running...!!!"
	exit
  fi

  # check directory termux-red
  if ! [ -d $PREFIX/../termux-red ];then
	mkdir $PREFIX/../termux-red
  fi

  # exit shell termux
  unset LD_PRELOAD

  # Kill processes on exit to avoid hanging on exit
  ARGS="--kill-on-exit"

  # mount point chroot
  # mount Linux file system android:
  for f in apex system vendor data storage sdcard sbin root sys dev proc; do
    if [ -d /$f ];then
	  ARGS="$ARGS -b /$f:/$f"
    fi
  done
  
  # Android 11.
  if [ -e "/linkerconfig/ld.config.txt" ]; then
	ARGS="$ARGS -b /linkerconfig/ld.config.txt:/linkerconfig/ld.config.txt"
  fi

  if [ -f /property_contexts ]; then
	# Used by getprop (see https://github.com/termux/termux-packages/issues/1076)
	# but does not exist on Android 8.
	ARGS="$ARGS -b /property_contexts:/property_contexts"
  fi
  
  # Mimic traditional Linux file system hierarchy - other Termux dirs:
  for l in bin etc include lib libexec share tmp var; do
     ARGS="$ARGS -b $PREFIX/$l:/$l"
  done
  
  # set sdcard to home
  for k in home kali-linux;do
    if [ -d $PREFIX/../$k ];then
    	ARGS="$ARGS -b $PREFIX/../$k:/$k"
	fi
  done

  # Set /home as current directory:
  ARGS="$ARGS --cwd=/home"

  # Root of the file system:
  ARGS="$ARGS -r $PREFIX/../termux-red"

  # Shell to execute:
  PROGRAM=/bin/bash
  if [ -x $HOME/.termux/shell ]; then
        PROGRAM=`readlink -f $HOME/.termux/shell`
  fi

  # export variable need
  export SHELL=/bin/bash
  export HOME=/home
  export SHOME=/sdcard/termux_home
  export -n PREFIX
  ARGS="$ARGS $PROGRAM -l"
  exec $PREFIX/bin/proot $ARGS
}

# running shell no-root termux-proot
if [ -f $PREFIX/bin/proot ]; then
	shellnoroot
	if ! [ -f $PREFIX/bin/xfce4-terminal ];then
		apt install xfce4-terminal
	fi
else
	apt install proot
fi
