#!/data/data/com.termux/files/usr/bin/bash

# check termux-proot running or not
if [[ $SHELL == "/bin/bash" ]];then
	#echo "[!] already running...!!!"
	exit
fi

# check directory chroot
if ! [ -d $PREFIX/../termux-red ];then
  mkdir $PREFIX/../termux-red
fi

# import directory to chroot
for i in bin etc lib tmp var; do
  if ! [ -d $PREFIX/../termux-red/$i ];then
    ln -s "$PREFIX/$i" "$PREFIX/../termux-red"
  fi
done

# exit shell termux
unset LD_PRELOAD

# mount point chroot
# mount Linux file system android:
for f in system vendor data storage sdcard sbin root sys dev proc; do
        ARGS="$ARGS -b /$f:/$f"
done

# set sdcard to home
if [ -d $HOME ];then
	ARGS="$ARGS -b $HOME:/home"
fi

# Set /home as current directory:
ARGS="$ARGS --cwd=/home"

# usr directory
for g in bin include lib libexec share man sbin; do
  if [[ $g == "sbin" ]];then
    ARGS="$ARGS -b /$g:/usr/$g"; continue
  fi
  ARGS="$ARGS -b $PREFIX/$g:/usr/$g"
done

# Root of the file system:
ARGS="$ARGS -r /data/data/com.termux/files/termux-red"

# Shell to execute:
PROGRAM=/bin/bash
if [ -x $HOME/.termux/shell ]; then
        PROGRAM=`readlink -f $HOME/.termux/shell`
fi

# export variable need
export SHELL=/bin/bash
export HOME=/home
export SHOME=/sdcard/termux_home
export -n PREFIX

# running shell no-root termux-proot
if [ -f $PREFIX/bin/proot ]; then
	ARGS="$ARGS $PROGRAM -l"
	exec $PREFIX/bin/proot $ARGS
else
	apt install proot
fi
